### ISSUE TITLE
Current M3UA implementation, drops connection when heartbeat is enabled

### ISSUE THREAD

**Issue by vazir** [wmnsk/go-m3ua#25]
All goes well, reading and writing works while HB interval set to 0
> (excerpt from sample m3ua client)
> hbInt = flag.Duration("hb-interval", 0, "Interval for M3UA BEAT. Put 0 to disable") 

when not zero, reader code fails after a few reads with the following error

2020/10/27 00:38:55 Read: deadbeef
2020/10/27 00:38:55 Error reading from M3UA conn: M3UA Conn not established
2020/10/27 00:38:55 Recovered from crash occurred on connection with: %!s(<nil>)

If HB is NOT enabled, that m3UA clent side does not understand the connection disappearance (until any write occures)

Sample code works, since there is HB = 0 in all configs and data direction is client to server
Testing is easy, just set HB interval to 1 and wait for a few packets to pass

**Comment by vazir** [comment]
@wmnsk any chance you could look at the issue?

**Comment by wmnsk** [comment]
For sure I will, but I don’t have time now. Thank you for your patience.

**Comment by vazir** [comment]
@wmnsk , I opened the pull request, with proposed fix

**Comment by wmnsk** [comment]
Great, thanks! I'll take a look later today.

**Comment by wmnsk** [comment]
Merged #26. Thank you for reporting & fixing it!
