### ISSUE TITLE
func Read reads data from the connection 

### ISSUE THREAD

**Issue by ProfCoinSoft** [wmnsk/go-m3ua#31]
Hi,

Please could you help me, give simple sample for uses func Read() in conn.go line 61:
func (c *Conn) Read(b []byte) (n int, err error)

How use its and how I can call its ?
Thanks!

**Comment by wmnsk** [comment]
You can see the sample usage here (the error handling below that is not a very good example, though).

https://github.com/wmnsk/go-m3ua/blob/master/examples/server/m3ua-server.go#L34

FYI, it implements the `io.Reader` interface, which is so popular as to be explained in A Tour of Go.

https://tour.golang.org/methods/21

**Comment by ProfCoinSoft** [comment]
Thanks very much!

**Comment by ProfCoinSoft** [comment]
How I can read answer, when i send to remote server data used:

if _, err  m3ua.Write(UDTS); err != nil {
....
}

Thanks!

**Comment by ProfCoinSoft** [comment]
My mistake - for this question needed read readme to project.

```
if _, err := conn.Write(d); err != nil {
    log.Fatalf("Failed to write M3UA data: %s", err)
}
log.Printf("Successfully sent M3UA data: %x", d)

buf := make([]byte, 1500)
n, err := conn.Read(buf)
if err != nil {
    log.Fatal(err)
}

log.Printf("Successfully read M3UA data: %x", buf[:n])
```
