### ISSUE TITLE
Is library support MultiHoming ?

### ISSUE THREAD

**Issue by ProfCoinSoft** [wmnsk/go-m3ua#33]
Hi!

How I can use MultiHoming in my project? I can use only this method, for one connect:

```
sctpLocalAddr := &sctp.SCTPAddr{
	IPAddrs:  "10.10.10.4",,
	Port:    9500,
}
sctpRemoteIP := &sctp.SCTPAddr{
	IPAddrs: "10.10.10.5",
	Port:    9501,
}
conn, err := m3ua.Dial(*ctx, "m3ua", sctpLocalAddr, sctpRemoteIP, m3conf)
```

Thanks for help!

**Comment by wmnsk** [comment]
Let me know if you need further help with something about this library.

**Comment by ProfCoinSoft** [comment]
> Linux SCTP sends all available addresses by default, so no need to specify multiple addresses explicitly.

Thanks you a lot for explanations!
