### ISSUE TITLE
When two SCTP messages arrives on the wire, only the second is returned by m3ua

### ISSUE THREAD

**Issue by vazir** [wmnsk/go-m3ua#47]
Dear @wmnsk 

Hit one bug, not sure where does it root comes from, but I traced to the wire:

When there is 2 messages on the SCTP returned as one packet, like that:

![image](https://user-images.githubusercontent.com/919929/234628513-2edef3f2-0305-4746-aaa9-c9491d81eac0.png)

On the m3ua side there is only the ending packet (end dtid in the picture), and the 1st one (request report bcsm report on the pic) is lost.

![image](https://user-images.githubusercontent.com/919929/234629406-b95f7253-3a2d-405d-982d-9f2837e1a2bd.png)

I will be grateful if you can look at it

**Comment by vazir** [comment]
I Traced it down to fsm.go monitor and it looks like it's something with the buffer got overwritten by second message as it arrives before the 1st one sent to a channel.

**Comment by vazir** [comment]
Problem is gone, if i shift buffer allocation into the cycle. But I have no idea how it will influence on memory (leak?) and performance

so if I shif `buf := make([]byte, 0xffff)` in the fsm.go inside the cycle

<pre>
			buf := make([]byte, 0xffff)
			n, info, err := c.sctpConn.SCTPRead(buf)
</pre>

It works and both content of 1st SCCP stream and following delivered to the client code correctly

Could you please look at?

**Comment by vazir** [comment]
I think the problem is because messages are parsed before GO handles the execution to a go-routine
> `go c.handleSignals(ctx, msg)`

Probably invoking directly `c.handleSignals(ctx, msg) ` instead of executing in backround could be a solution

or the buffer pool may be an option ?

**Comment by wmnsk** [comment]
Thanks for the analysis, that should help a lot. Let me have a look at the code (and other projects of mine using the same sctp library) to figure out what is the problem. I think I will have some time this evening or tomorrow.

**Comment by wmnsk** [comment]
Fix merged https://github.com/wmnsk/go-m3ua/pull/48
I believe it should resolve, but let me know in case it doesn't.
